apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: dns-agent-system
  labels:
    app.kubernetes.io/name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console

