apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: dns-agent-system
type: Opaque
stringData:
  accesskey: minioadmin
  secretkey: minioadmin
  endpoint_url: http://minio:9000
  bucket: lightningstream
  region: us-east-1
