apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: dns-operator-metrics
    files:
      - dnszones.yaml
      - dnsrecordsets.yaml
    options:
      labels:
        telemetry.miloapis.com/resource-metrics-config: "true"
