apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: dns.networking.miloapis.com-dnsrecordset-admin
  annotations:
    kubernetes.io/display-name: DNS RecordSet Admin
    kubernetes.io/description: "Full access to DNSRecordSet resources"
spec:
  launchStage: Beta
  inheritedRoles:
    - name: dns.networking.miloapis.com-dnsrecordset-viewer
  includedPermissions:
    - dns.networking.miloapis.com/dnsrecordsets.create
    - dns.networking.miloapis.com/dnsrecordsets.update
    - dns.networking.miloapis.com/dnsrecordsets.patch
    - dns.networking.miloapis.com/dnsrecordsets.delete


