apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: dns.networking.miloapis.com-dnszone-viewer
  annotations:
    kubernetes.io/display-name: DNS Zone Viewer
    kubernetes.io/description: "View access to DNSZone resources"
spec:
  launchStage: Beta
  includedPermissions:
    - dns.networking.miloapis.com/dnszones.list
    - dns.networking.miloapis.com/dnszones.get
    - dns.networking.miloapis.com/dnszones.watch
    - dns.networking.miloapis.com/dnszoneclasses.list
    - dns.networking.miloapis.com/dnszoneclasses.get
    - dns.networking.miloapis.com/dnszoneclasses.watch


