# This rule is not used by the project dns-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to dns.networking.miloapis.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dns-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsrecordset-viewer-role
rules:
- apiGroups:
  - dns.networking.miloapis.com
  resources:
  - dnsrecordsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.networking.miloapis.com
  resources:
  - dnsrecordsets/status
  verbs:
  - get
