apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dns-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnszonediscovery-editor-role
rules:
- apiGroups:
  - dns.networking.miloapis.com
  resources:
  - dnszonediscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.networking.miloapis.com
  resources:
  - dnszonediscoveries/status
  verbs:
  - get


