- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: downstream-kubeconfig
    secret:
      secretName: downstream-kubeconfig
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: downstream-kubeconfig
    mountPath: /downstream
    readOnly: true



