apiVersion: v1
kind: Service
metadata:
  name: pdns-auth
spec:
  selector:
    app.kubernetes.io/name: pdns-auth
  ports:
  - name: dns
    port: 53
    targetPort: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: api
    port: 8082
    targetPort: 8082
    protocol: TCP
  - name: metrics
    port: 8083
    targetPort: 8083
    protocol: TCP
  - name: dnscol-metrics
    port: 8084
    targetPort: 8084
    protocol: TCP
  - name: dnscolt-metrics
    port: 9165
    targetPort: 9165
    protocol: TCP
  - name: vector-metrics
    port: 9598
    targetPort: 9598
    protocol: TCP
